name: NHL daily results to Telegram (sports.ru)

on:
  schedule:
    # GitHub Actions использует UTC. Ниже — 05:45 UTC, что соответствует 06:45 Europe/London,
    # как правило уже после последнего матча в Северной Америке.
    - cron: "45 5 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python nhl_daily_results_bot.py
